version: "2.1"

networks:
  ps:

services:
  newer:
    image: newer
    container_name: ps-nwersrv
    ports:
      - "127.0.0.1:8001:8001"
    healthcheck:
      test: ["CMD-SHELL", "netstat -ltn | grep -c 8001"]
    networks:
      - ps

  prometheus:
    image: prom/prometheus:latest
    volumes: 
      - ./prometheus:/prometheus/
    command:
      - --config.file=/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss:9.4.3
    ports:
      - "3000:3000"
    volumes: 
      - grafana-data:/var/lib/grafana

  clickhouse-db:
    image: clickhouse/clickhouse-server:latest
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: qwerty123
    ports:
      - "8123:8123"
      - "9000:9000"

volumes:
  grafana-data: