scrape_configs:
  - job_name: 'prometheus'
    scrape_interval:     15s
    scrape_timeout:      15s
    static_configs:
      - targets: ['localhost:9090']
      - targets: ['host.docker.internal:8001']

  - job_name: 'clean_server'
    scrape_interval:     15s
    scrape_timeout:      15s
    static_configs:
      - targets: ['host.docker.internal:8001']  # доступ к прометеусу внутри докера, чтобы не ставить на свой комп
